### PR TITLE
Resolve undefined property lookup on mocha file name formatting

### PR DESCRIPTION
**Pull request by zjkipping**
Should help resolve issue: https://github.com/michaelleeallen/mocha-junit-reporter/issues/178

### CODE REVIEW

**Comment by zjkipping** [comment]
@clayreimann Any way this can be fast tracked this is ruining a rather large monorepo on my client project.

**Comment by zjkipping** [comment]
If there is a better default value other than just an empty string, I am happy to replace that. I just don't know the direction this repo would like to go on the topic.

**Comment by clayreimann** [comment]
@zjkipping Can you explain what happens if we generate a file with the empty string as a name?

**Comment by zjkipping** [comment]
> @zjkipping Can you explain what happens if we generate a file with the empty string as a name?

Currently if you had a file name of `foo-[suitName]-bar` it would look like `foo--bar`. Which is why I mentioned we might want something besides the `''` default value. I figured someone else might have a better idea about that since I mostly just came to fix the fact it exits as an error currently. possibly just something like `'suitName'` could be a fine default or `'undefined'`.

**Comment by clayreimann** [comment]
Would you update the default values to be the bracketed thing that we're, maybe, replacing?

**Comment by zjkipping** [comment]
@clayreimann Done, let me know if there is anything else I can do with the PR.

**Comment by zjkipping** [comment]
@clayreimann Looks like the github actions pipelines are failing. Is that a concern for pushing out a `2.2.1` version of the npm package? Not super trying to rush you since I realize this is open source, but I would like to be able to consume this in my client project. If there is anything I can do to support a patch version publish please let me know, happy to help.

**Pull request merged**
