### PR TITLE
Implemented support for custom suite generator

### PR DESCRIPTION
**Pull request by stalniy**

### CODE REVIEW

**Comment by clayreimann** [comment]
Looks good. Can you update the Readme to reflect this feature?

**Comment by stalniy** [comment]
I decided to restrict this because I think usually people want to have full or not full title

**Comment by clayreimann** [comment]
Can you pull the fix for #24 out of this PR?

**Comment by stalniy** [comment]
Close this. Will create new one. Sorry that mixed up different stuff

**Pull request closed without merging**
