### PR TITLE
Show stack traces in failure output, bump package to 1.7.0.

### PR DESCRIPTION
**Pull request by akhaku**
Anything else we need to do to push to npm?
Also, feedback on changes appreciated.

### CODE REVIEW

**Comment by akhaku** [comment]
Heya - any time to look at this?

**Comment by clayreimann** [comment]
@michaelleeallen can you add someone else as a collaborator in npm or look at the auto-publish stuff

**Comment by michaelleeallen** [comment]
@clayreimann I will take a look

**Comment by michaelleeallen** [comment]
@clayreimann you should be an npm collaborator now

**Pull request merged**
