### PR TITLE
Add support for properties within testsuites.

### PR DESCRIPTION
**Pull request by mikeng13**
Need support for properties values within the test suites.

### CODE REVIEW

**Comment by clayreimann** [comment]
Can you please add documentation about what this is/how it's used.

**Comment by mikeng13** [comment]
@clayreimann I added another section to the README to document it!

**Comment by clayreimann** [comment]
👍 Looks good. Thanks for the feature!

**Comment by clayreimann** [comment]
@mikeng13 `v1.11` now available with your addition.

**Comment by mikeng13** [comment]
Thanks a lot @clayreimann

**Pull request merged**
